[package]
name = "Haochong-individual-2"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
reqwest = { version = "^0.11", features = ["blocking"] }
rusqlite = "0.23.1"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html